version: "3"
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["sh", "docker_cmd.sh"]
  # データベース
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    user: "${UID}:${GID}"
    env_file:
      .env

    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/app
      - /Users/manh_nguyen/mysql/data:/var/lib/mysql
      - /Users/manh_nguyen/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
